export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const SET_PROFILE = 'SET_PROFILE';
export const TOGGLE_SORT_ORDER = 'TOGGLE_SORT_ORDER';
export const SET_ROLE_FILTER = 'SET_ROLE_FILTER';
export const SET_ARCHIVE_FILTER = 'SET_ARCHIVE_FILTER';
export const SAVE_PROFILE = 'SAVE_PROFILE';